### ISSUE TITLE
Could not customize the tabBarSwitchSelectedColor

### ISSUE THREAD

**Issue by Ngsetest** [Giphy/giphy-ios-sdk-ui-example#137]
Hello, I am using swift example app. Trying to override GPHTabBarButton image color, but it has no effect.
![image](https://user-images.githubusercontent.com/29040713/105865165-51477680-5ffb-11eb-8c6d-a1af35115a4d.png)
Giphy SDK version 2.1.1, iOS 14.1

**Comment by cgmaier** [comment]
hey @Ngsetest thanks for catching this. we'll include a fix in the next release.

**Comment by cgmaier** [comment]
hey @Ngsetest this is fixed with the latest release. 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.1.2
thanks!

**Comment by Ngsetest** [comment]
Hey @cgmaier thx for you help. But now I still see the wrong color. I set it to red/yellow/green, but I always get blue :)
![image](https://user-images.githubusercontent.com/29040713/108270878-b44ea800-7178-11eb-8876-04cd98098178.png)
Giphy SDK version 2.1.5, iOS 14.1
