### ISSUE TITLE
I keep getting this warning with Carthage Kit

### ISSUE THREAD

**Issue by h36ahmed** [Giphy/giphy-ios-sdk-ui-example#31]
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/PURJ2OO6CDH7/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
![image](https://user-images.githubusercontent.com/13081913/65811701-7f5c4280-e18a-11e9-9e28-ae7fdb52d55d.png)

**Comment by h36ahmed** [comment]
And I use CocoaPods not Carthage.

**Comment by cgmaier** [comment]
hey @h36ahmed that's odd! we'll look into it. are you seeing this on the latest version of the GIPHY SDK (v1.1.2)? in which version did you start seeing in the warning? 

we use Carthage for compiling the SDK.

**Comment by h36ahmed** [comment]
I started seeing since v1.1. I am using 1.1.2 now.

**Comment by zeusent** [comment]
Me too. I see a lot of these:

```
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/PURJ2OO6CDH7/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/PURJ2OO6CDH7/Foundation-3DFYNEBRQSXST.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/OMSDK_Giphy-1V2AMKGI68IJW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/OMSDK_Giphy-1V2AMKGI68IJW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk/2.1.4/ModuleCache.noindex/149BKCZGJ6XW1/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/2VFM03HXSST1U/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/2VFM03HXSST1U/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/CommonCrypto-3IJ2UQT7UNSLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/CommonCrypto-3IJ2UQT7UNSLI.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/AdSupport-39FV6ZG206YYE.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A419c/giphy-ios-sdk-analytics/0d30d2c51764e9dcd68bc93338da368980e64717/ModuleCache.noindex/DBZ6X041KJ6I/AdSupport-39FV6ZG206YYE.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/QuartzCore-23I9VTX2KZMTH.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/ImageIO-YVI44K06S0WO.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/ImageIO-YVI44K06S0WO.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Accelerate-1IKW7DALYIORV.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/Accelerate-1IKW7DALYIORV.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/MobileCoreServices-3PK2VQ0R2SYLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/MobileCoreServices-3PK2VQ0R2SYLI.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/AssetsLibrary-15E86WRBMI1ZI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/AssetsLibrary-15E86WRBMI1ZI.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/zlib-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/26JZ3JV32HPJE/zlib-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/GiphyUISDK-3MZVL9YY0LVDB.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/GiphyUISDK-3MZVL9YY0LVDB.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/PINCache-3XBPRZQJY2O8.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/PINCache-3XBPRZQJY2O8.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/234U0RVQBNDWF/QuartzCore-23I9VTX2KZMTH.pcm
````

Maybe the notes in there is of some help?

> Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information

**Comment by cgmaier** [comment]
thanks @h36ahmed / @zeusent ! sorry about the big warnings - we'll definitely fix with the next release.

**Comment by cgmaier** [comment]
hey @h36ahmed / @zeusent sorry for the delay on this. this should be fixed now with [v1.1.3](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.1.3)

**Comment by zeusent** [comment]
Thanks @cgmaier! I’ll give this a shot

**Comment by zeusent** [comment]
@cgmaier I still see the warnings unfortunately :(

```
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/177KPPO7Z4OG8/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/177KPPO7Z4OG8/Foundation-3DFYNEBRQSXST.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/OMSDK_Giphy-1V2AMKGI68IJW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/OMSDK_Giphy-1V2AMKGI68IJW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.6/ModuleCache.noindex/13IRXX75APCZG/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/2VFM03HXSST1U/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/2VFM03HXSST1U/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/CommonCrypto-3IJ2UQT7UNSLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/CommonCrypto-3IJ2UQT7UNSLI.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/AdSupport-39FV6ZG206YYE.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk-analytics/f1e822acf5623b1baa1f8381b517fb3ee0df3350/ModuleCache.noindex/DBZ6X041KJ6I/AdSupport-39FV6ZG206YYE.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/QuartzCore-23I9VTX2KZMTH.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/ImageIO-YVI44K06S0WO.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/ImageIO-YVI44K06S0WO.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Accelerate-1IKW7DALYIORV.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/Accelerate-1IKW7DALYIORV.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/MobileCoreServices-3PK2VQ0R2SYLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/MobileCoreServices-3PK2VQ0R2SYLI.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/AssetsLibrary-15E86WRBMI1ZI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/AssetsLibrary-15E86WRBMI1ZI.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/zlib-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1VVHXX92SKDMJ/zlib-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/GiphyUISDK-3MZVL9YY0LVDB.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/GiphyUISDK-3MZVL9YY0LVDB.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/PINCache-3XBPRZQJY2O8.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/PINCache-3XBPRZQJY2O8.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/2IGTKPEQH440Q/QuartzCore-23I9VTX2KZMTH.pcm
```

**Comment by cgmaier** [comment]
ah okay - thanks for testing @zeusent ! I haven't actually been able to repro on my machine, but thought disabling module debugging might do it. i'll take another look at this

**Comment by zeusent** [comment]
I didn't actually updated 1.1.3 the first time @cgmaier. Here's an updated log:

```
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/OMSDK_Giphy-3ER33CL9T2KHR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/OMSDK_Giphy-3ER33CL9T2KHR.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/AdSupport-39FV6ZG206YYE.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/AdSupport-39FV6ZG206YYE.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CommonCrypto-3IJ2UQT7UNSLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CommonCrypto-3IJ2UQT7UNSLI.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/GiphyUISDK-3MZVL9YY0LVDB.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/GiphyUISDK-3MZVL9YY0LVDB.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/PINCache-3XBPRZQJY2O8.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/PINCache-3XBPRZQJY2O8.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/QuartzCore-23I9VTX2KZMTH.pcm
```

**Comment by h36ahmed** [comment]
Having the same issues still

**Comment by timurbeg** [comment]
We are still seeing below warnings in the latest version of Giphy 1.1.3:
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
Module debugging should be disabled when shipping static libraries.

**Comment by cgmaier** [comment]
hey all - really sorry about the delay on this. i'll advocate for it to be a priority for next week. thanks for all the great feedback.

**Comment by cgmaier** [comment]
hey all - oddly enough, nobody on our iOS team here can reproduce the warnings, and so I'm not sure what to do in order to fix it. I disabled "module debugging" with the last release though that hasn't seemed to fix the issue for you guys. 

i was wondering if it has to do with a Cocoapods version.  I'm on the latest (`1.8.4`), but also couldn't repro the warnings before i updated (from `1.7.1`, i think) so I'm skeptical that's it. in any case could you guys verify your Cocoapods version? 
  
more likely, there's a build setting i haven't gotten quite right. I'll keep on poking around but please let me know if you guys have any ideas. 
 
cc @timurbeg @zeusent @h36ahmed

**Comment by zeusent** [comment]
I’m running the latest version of Cocoapods as well... I don’t have Cartage installed at all. Since I’m seeing something related to it in the warnings maybe that could have something to do with it?

**Comment by cgmaier** [comment]
dang ! @zeusent i just tried uninstalling carthage & all of its folders & still not able to repro. i imagine youre also on the latest version of xcode? are you using swift? 
would you also mind doing a fresh install of GIPHY via: 
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

if it's not too much trouble !

**Comment by timurbeg** [comment]
@cgmaier  I've tried fresh install. But I'm still seeing warnings + there is a warning on "import GiphyCoreSDK" - Implicit import of bridging header 'GiphyCoreSDK-Bridging-Header.h' via module 'GiphyCoreSDK' is deprecated and will be removed in a later version of Swift:
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/3EVHOM4AIXCNF/Foundation-3DFYNEBRQSXST.pcm
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Dispatch-2LX9MWM6UEPQW.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Darwin-38I6DLZ5IH61J.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SystemConfiguration-354UAJE49HRJF.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SystemConfiguration-354UAJE49HRJF.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/OMSDK_Giphy-3ER33CL9T2KHR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/OMSDK_Giphy-3ER33CL9T2KHR.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/AdSupport-39FV6ZG206YYE.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/AdSupport-39FV6ZG206YYE.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CommonCrypto-3IJ2UQT7UNSLI.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CommonCrypto-3IJ2UQT7UNSLI.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/giphy-ios-sdk/2.1.7/ModuleCache.noindex/9SRYF3BPRVEJ/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/UIKit-1V5UHAPTOD24G.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/Foundation-3DFYNEBRQSXST.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/ObjectiveC-1R06XOY9T4FIM.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/ObjectiveC-1R06XOY9T4FIM.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/GiphyUISDK-3MZVL9YY0LVDB.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/GiphyUISDK-3MZVL9YY0LVDB.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/PINCache-3XBPRZQJY2O8.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/PINCache-3XBPRZQJY2O8.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreGraphics-54UV9QOCX3ZY.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreGraphics-54UV9QOCX3ZY.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/SwiftShims-2TTN5UXQBRCCQ.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/SwiftShims-2TTN5UXQBRCCQ.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/CoreFoundation-J9ZOXGK4ZTRR.pcm
warning: /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/QuartzCore-23I9VTX2KZMTH.pcm: No such file or directory
note: while processing /Users/chrismaier/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/3BM64UROQEBCQ/QuartzCore-23I9VTX2KZMTH.pcm

**Comment by cgmaier** [comment]
ah I've finally repro'd. looks like it happens when actually _archiving_ a build rather than just running. is this the same for you? do these warnings prevent you from successful submission?

**Comment by timurbeg** [comment]
Nope. It doesn't. I just want to keep project clean. Maybe in future you will be able to fix it or this issue will be gone itself... Anyway thanks.

**Comment by zeusent** [comment]
Hey @cgmaier! First, let me say thanks for putting time and effort into this. As @timurbeg said this doesn't seem to affect submission. It's rather trying to clean up the project and not have a handful of warnings on compile time. For me it's happening when debugging as well but I guess as long as you've managed to reproduce it in someway it's a sign your on the right track. If I could do anything to help you let me know.

Thanks again!

**Comment by wvdk** [comment]
I'm also getting these warnings. Not prohibiting development or release but I would love to see a fix for this. Kinda makes our No Warnings policy feel silly. Folks seem to think if there are already a bunch of warnings in the project they don't need to clean up their new ones :P

**Comment by EmperiorEric** [comment]
We are seeing this issue as well. It doesn't specifically prohibit development, but it makes it impossible for us to treat warnings as errors.

**Comment by cgmaier** [comment]
hey guys thanks so much for using the UI SDK & noting this as something you care about ! we really want to work on this. I hope we can get this done before the holidays. 

another priority is achieving Swift compatibility so we don't have to push a new release whenever a new version of Swift is released - unfortunately this has proven a bit trickier than expected and so that aspect of things may need to wait for the new year, and we will push new versions whenever necessary.

similar to my note on Issue relating to Carthage, please email sdk@giphy.com with the name of your app and your requests if you haven't already - this could help loop in our SDK partnerships team about the importance of squashing these warnings so we can make the SDK much nicer to use ! they also always like to be connected with teams & apps who want to use GIPHY

**Comment by cgmaier** [comment]
hey ! i just pushed an update, v1.1.7, which should solve most of these warnings caused by the GIPHY SDK.

**Comment by wvdk** [comment]
Nope, doesn't fix the warnings we are reporting in this ticket. It has something to do with Carthage and your personal DerivedData directory.

```
warning: /Users/chrismaier/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/giphy-ios-sdk/518dacd960bd9d0ce50eab2dab9f2c39449c9b1f/ModuleCache.noindex/2WBAOTLZFM72/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
```

**Comment by cgmaier** [comment]
confirmed, they're still there. sorry about that.

**Comment by drewolbrich** [comment]
I'm seeing this too, although I am still on 1.1.6 and I just noticed that 1.1.7 was released. I'll try it now.

(1.1.6 screenshot)
![Screen Shot 2019-12-11 at 11 27 50 AM](https://user-images.githubusercontent.com/12141562/70667115-f69b6180-1c24-11ea-8080-e93dd7a95d05.png)

**Comment by drewolbrich** [comment]
Using Cocoapods, I am still seeing the /Users/chrismaier Carthage warnings with Giphy 1.1.7.

![Screen Shot 2019-12-11 at 2 50 57 PM](https://user-images.githubusercontent.com/12141562/70667415-ac66b000-1c25-11ea-9694-c185d2abcc6b.png)

**Comment by drewolbrich** [comment]
@cgmaier btw thanks for providing the Giphy SDK. It has been a pleasure to use and has saved me a huge amount of development time on our project. 😄

**Comment by cgmaier** [comment]
thanks @drewolbrich @wvdk 

these warnings have been quite persistent! i did a deep dive into Xcode build settings the past few days and I'm fairly certain these are gone once and for all with GIPHY 1.1.8

**Comment by wvdk** [comment]
Can confirm - only warnings are my own fault. Thank you @cgmaier!

**Comment by drewolbrich** [comment]
@cgmaier thank you Christopher you are awesome !!!

![Screen Shot 2019-12-12 at 4 35 28 PM](https://user-images.githubusercontent.com/12141562/70760123-86acda00-1cfd-11ea-9131-c97506d1fcc9.png)

![dancing-geometry](https://user-images.githubusercontent.com/12141562/70760109-73017380-1cfd-11ea-9c0e-b67c18e75b74.gif)

**Comment by johntmcintosh** [comment]
@cgmaier I'm facing similar warnings for consumers of an SDK that's distributed as a precompiled binary. Would you mind sharing what you eventually changed in your [1.1.8 release](https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v1.1.8) that resolved these warnings?

**Comment by cgmaier** [comment]
hey @johntmcintosh sorry for the late reply. i think it was this SO answer that helped me 
https://stackoverflow.com/questions/33206431/ios-how-to-fix-the-following-warning-issues
