### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by mdescalzo** [Giphy/giphy-ios-sdk-ui-example#37]
I have some projects already using Carthage in which I'd like to use the Giphy framework.  Could you please look into adding Carthage support?

**Comment by cgmaier** [comment]
hey thanks for reaching out ! i noted this request to my team - hopefully we can get to this at some point

**Comment by Drusy** [comment]
Carthage support would be great !
In the meanwhile, do you provide the compiled frameworks outside of Cocoapods ?
We do not wish to include Cocoapods for a single framework unfortunately

**Comment by cgmaier** [comment]
hey @Drusy, @mdescalzo and anyone else ! 

please email sdk@giphy.com with the name of your app and your requests - this could help loop in our SDK partnerships team about the importance of having method of integrating the SDK (alternative to cocoapods) so we can better prioritize it. they also always like to be connected with teams & apps who want to use GIPHY : ) 

i of course to hope to get to this regardless but can't promise anything 

@Drusy - i don't think there's any problem in sharing these with you (this is what `pod 'Giphy'` pulls in), however, i'm concerned you may have trouble linking the SDK's dependencies. I have not tested this so you're on your own unfortunately. definitely let me know how it goes please ! 

https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.1.4/GiphySDK.zip
https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.1.4/Giphy.podspec
^ the podspec for clarifying dependencies

**Comment by Drusy** [comment]
Hey @cgmaier,

Thanks for the links, it will help us for now. We can pull `DeepDiff` and `PINCache` from Carthage as they are fully compatible. `libwebp` is a bit more complicated for now and we need to script the framework compilation.
Some library are compatible with Carthage but seem to include `libwebp` as a submodule and compile it right in the project I guess. Here is an example https://github.com/ainame/Swift-WebP

I will definitely contact you on sdk@giphy.com if it may help to prioritize. Unfortunately for now, I don't see us using this SDK seriously if it forces us to use Cocoapods. It's too much energy for updating a single dependency.

**Comment by cgmaier** [comment]
Thanks @Drusy !

**Comment by mdescalzo** [comment]
@cgmaier Thanks!  I'll look at the links when that facet of the project circles back to it.  There's no linkable app just yet.  We're still in development.

**Comment by ammerzon** [comment]
I also gave the SDK a try with Carthage. I added all the required dependencies to my Cartfile and downloaded the Giphy framework as you can see below. For `libwebp` I used a wrapper from SDWebImage.

**Cartfile.resolved**
```
github "onmyway133/DeepDiff" "2.3.1"
github "pinterest/PINCache" "2.3"
github "SDWebImage/libwebp-Xcode" "1.0.3"
```
[GiphySDK 1.1.5](https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.1.5/GiphySDK.zip)

**Carthage build phase**
<img width="916" alt="Screenshot 2019-12-13 at 11 05 01" src="https://user-images.githubusercontent.com/7319168/70792022-a47b4d00-1d98-11ea-91cd-1b2bf621abca.png">

<img width="910" alt="Screenshot 2019-12-13 at 11 06 14" src="https://user-images.githubusercontent.com/7319168/70792021-a3e2b680-1d98-11ea-8a5a-e5a638e6bbd6.png">

Unfortunately I am now getting the following errors:
<img width="526" alt="Screenshot 2019-12-13 at 11 08 58" src="https://user-images.githubusercontent.com/7319168/70792317-38e5af80-1d99-11ea-8489-89d04ea01e83.png">

Does anyone know how to get the undefined symbols?

**Comment by cgmaier** [comment]
hey @ammerzon - we're looking at officially supporting carthage in the coming year  

in the mean time, i think you might have look try adding an additional entry in input files: 

`...iOS/GiphyCoreSDK.framework/omsdk-ios-1.2.20-Giphy/OMSDK_Giphy.framework` 

and in output files: 
`...$(FRAMEWORKS_FOLDER_PATH)/OMSDK_Giphy.framework`

have no idea if this will work, but worth a try. let me know either way !

**Comment by ammerzon** [comment]
That is great to hear 🎉

<img width="1114" alt="Screenshot 2019-12-16 at 18 35 42" src="https://user-images.githubusercontent.com/7319168/70929324-2be3ed00-2033-11ea-8242-50485d90cc58.png">

Unfortunately, it now complains that the bundle format is unrecognized, invalid, or unsuitable.

**Comment by cgmaier** [comment]
could you try `GiphyCoreSDK.framework/Frameworks/OMSDK_Giphy.framework` instead?

**Comment by ammerzon** [comment]
I also tried that but it leads to the same result as above.

**Comment by cgmaier** [comment]
hmm maybe a framework search paths thing (in build settings?) 

sorry i can't be of more help here

**Comment by cgmaier** [comment]
hey all ! sorry for the delay on this. think I've got distribution / installation through Carthage working. we'll hopefully "officially" release / document Carthage support soon but wanted to give you a chance to test it out first: 

**Carthage Setup**

1. Add GiphySDK to your Cartfile:
```
binary "https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/GiphySDK.json"
```
2. Add `-Objc` to the `Other Linker Flags` Build Setting

3. Add `PINCache.framework`, `DeepDiff.framework`, `GiphyCoreSDK.framework`, `GiphyUISDK.framework`, `WebP.framework`, and `OMSDK_Giphy.framework` from `Carthage/Build/iOS` into your project. (`OMSDK_Giphy.framework` can be found inside of the `GiphyCoreSDK.framework`)

4. Create a new Run Script under Build Phases (See step 8 of the directions [here](https://github.com/Carthage/Carthage#quick-start)). Only 4 of the frameworks need to be added to the run script (Both `WebP.framework` and `OMSDK_Giphy.framework` can be excluded from this step): 

- `GiphyCoreSDK.framework` 
- `PINCache.framework` 
- `GiphyUISDK.framework` 
- `DeepDiff.framework` 

cc @ammerzon @Drusy @mdescalzo

**Comment by Drusy** [comment]
Hey @cgmaier, thanks for your efforts.

The project compiles well with this integration. However, I can't make the UI framework work properly.
When I try to show a `GiphyViewController()`, I have the following error

```
2020-01-24 10:14:26.587820+0100 giphy-carthage[62050:2078034] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GiphyUISDK.GiphySearchController registerKeyboardNotifications]: unrecognized selector sent to instance 0x7ffe48424740'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff480c0f17 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	5   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	6   giphy-carthage                      0x000000010daeae90 $s10GiphyUISDK0A16SearchControllerC13noResultsViewAA05GPHNoF0CvgTo + 160
	7   UIKitCore                           0x00007fff47a19d47 -[UIViewController _setViewAppearState:isAnimating:] + 663
	8   UIKitCore                           0x00007fff47a1a479 -[UIViewController __viewWillAppear:] + 115
	9   UIKitCore                           0x00007fff47978726 -[UINavigationController _startTransition:fromViewController:toViewController:] + 718
	10  UIKitCore                           0x00007fff479793b6 -[UINavigationController _startDeferredTransitionIfNeeded:] + 868
	11  UIKitCore                           0x00007fff4797a721 -[UINavigationController __viewWillLayoutSubviews] + 150
	12  UIKitCore                           0x00007fff4795b553 -[UILayoutContainerView layoutSubviews] + 217
	13  UIKit                               0x000000010ff4dae1 -[UILayoutContainerViewAccessibility layoutSubviews] + 42
	14  UIKitCore                           0x00007fff485784bd -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	15  QuartzCore                          0x00007fff2b131db1 -[CALayer layoutSublayers] + 255
	16  QuartzCore                          0x00007fff2b137fa3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 517
	17  UIKitCore                           0x00007fff48563635 -[UIView(Hierarchy) layoutBelowIfNeeded] + 980
	18  giphy-carthage                      0x000000010dacead5 $s10GiphyUISDK0A14ViewControllerC17animateTransition5usingySo06UIViewD20ContextTransitioning_p_tF + 725
	19  giphy-carthage                      0x000000010dacef49 $sSo23UIViewAnimatingPositionVIegy_ABIeyBy_TR + 105
	20  UIKitCore                           0x00007fff47a42cf5 ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 54
	21  UIKitCore                           0x00007fff47b5af7e +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
	22  UIKitCore                           0x00007fff47a42c89 ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
	23  UIKitCore                           0x00007fff4856a351 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
	24  UIKitCore                           0x00007fff47a42b0f _UIViewControllerTransitioningRunCustomTransition + 553
	25  UIKitCore                           0x00007fff47924740 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.465 + 2632
	26  UIKitCore                           0x00007fff4809be5b _runAfterCACommitDeferredBlocks + 352
	27  UIKitCore                           0x00007fff4808c7b4 _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	28  UIKitCore                           0x00007fff480bc3a9 _afterCACommitHandler + 85
	29  CoreFoundation                      0x00007fff23bd3867 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	30  CoreFoundation                      0x00007fff23bce2fe __CFRunLoopDoObservers + 430
	31  CoreFoundation                      0x00007fff23bce97a __CFRunLoopRun + 1514
	32  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	33  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	34  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	35  giphy-carthage                      0x000000010da4b79b main + 75
	36  libdyld.dylib                       0x00007fff5227ec25 start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
```

I also tried to add a `GPHMediaView` to my view. I can easily get a media using `GiphyCore.shared.gifByID` but nothing is showing and I have no error log and `error` is nil in the callback

```swift
GiphyCore.shared.gifByID("7bWtoBmjn6fAI") { (response, error) in
    if let media = response?.data {
        DispatchQueue.main.sync { [weak self] in
            self?.giphyView.media = media
        }
    }
}
```

**Comment by cgmaier** [comment]
Hey @Drusy thanks so much for giving this a shot! My apologies - it looks like I wrote `-Objc` rather than `-ObjC` for the build setting. Adding `-ObjC` to `Other Linker Flags` should fix the crash you note. I'll work on making it not necessary to set this build setting in the future. 

I'll look into the `GPHMediaView` issue and get back to you.

**Comment by Drusy** [comment]
Sorry, I should have used the correct flag indeed ... The controller works like a charm. The `GPHMediaView` still appears to be broken.

**Comment by cgmaier** [comment]
thanks for confirming ! it was my bad actually - i initially wrote the flag incorrectly.  

re `GPHMediaView`, good catch - there's another issue with our documentation. simply setting the `media` property on the flag doesn't do anything. you must explicitly call `setMedia`. sorry about that! we'll definitely fix this and make that property only as a get

**Comment by Drusy** [comment]
It works using `setMedia`

> we'll definitely fix this and make that property only as a get

Definitely sounds like a good idea !

Congratulations, you seem to officially support Carthage !
The last step would be to submit a Testflight build to ensure that the archive process is fine.

Thanks for this feature 👏

**Comment by cgmaier** [comment]
another good call @Drusy !

per your suggestion of testing archive / distribution, I noticed another issue - only two of the frameworks (`PINCache` and `DeepDiff`) should be included in the run script step, as the rest are static frameworks. I updated my previous comment which had the carthage setup instructions. 

thanks for your help!
