### ISSUE TITLE
Error on downloading version 1.2.9 with Carthage update

### ISSUE THREAD

**Issue by ezzz** [Giphy/giphy-ios-sdk-ui-example#70]
I am new to Giphy and would like to test it
I followed the Carthage update notes and added to Carthage file: 
binary "https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/GiphySDK.json"

I have an error with the zip which seems to be related to the access of the zip file of 1.2.9 that cannot be downloaded

With 1.2.8 download is OK but then I have an error at compilation related to Swift version, so it is not really better

Thanks for any help or advice

**Comment by cgmaier** [comment]
hey @ezzz ! thanks for flagging this issue. I'll look into it soon 

in the meantime a few follow up q's: 
- what version of Xcode are you using? 
- are you unable to use Cocoapods to install the SDK, instead of Carthage?

**Comment by devny** [comment]
@cgmaier I have same issue!!

**Comment by ezzz** [comment]
hello @cgmaier !

I use Xcode 11.5 coming with the iOS 13.5 update
For me the error seems quite easy to fix, so as we are only using Carthage in our project I will see how long it takes and if its too long then maybe give a try with Cocoapods.

**Comment by imnak0** [comment]
I have the same problem and hope it's fixed soon.
Here's the error message with v1.2.9 binary download

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9C2A47269308884E</RequestId>
<HostId>hUOi+a21EiSQl1cwRsfAiOIwsK6K5zGyYRvq6EncTMB3IWrYup07+f0yJEn99ZpD/iZjI76h2E8=</HostId>
</Error>
```

**Comment by devny** [comment]
hello @cgmaier 

I am curious when this issue will be resolved.

**Comment by cgmaier** [comment]
hey @devny I apologize for the delay! I fixed the error for v1.2.9 binary download per @imnak0's comment, however I was unable to successfully build a test app with the GIPHY dependency following Carthage update. feel free to try yourself, if possible! 

I hope to get to it soon regardless. thanks for your patience

**Comment by devny** [comment]
@cgmaier 
 
Well you still shouldn't use Carthage, what should I do?

The following error occurs.

   End-of-central-directory signature not found. Either this file is not
   a zipfile, or it constitutes one disk of a multi-part archive. In the
   latter case the central directory and zipfile comment will be found on
   the last disk(s) of this archive.

**Comment by devny** [comment]
@cgmaier 

I am still getting the following error in version 1.2.9, and I wonder how I tested it.

Incompatible Swift version-framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).

I am using Xcode 11.5 version.
In Carthage File

# Giphy SDK
binary "https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/GiphySDK.json" == 1.2.9

After writing this, I ran the command carthage update --platform iOS --cache-builds in Terminal.

**Comment by cgmaier** [comment]
hey @devny thanks for testing this out. it's possible your still pulling in the v1.2.9 that's already cached on your machine. clear the cache with: 
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```
then call 
```
carthage update --platform ios 
```

**Comment by devny** [comment]
@cgmaier 

Good morning. I tried entering the command as mentioned above and proceeded, but I still get the following error.

*** Downloading GiphySDK.framework binary at "1.2.9"
Incompatible Swift version-framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).

My Carthage File is as below.

# Giphy SDK
binary "https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/GiphySDK.json" == 1.2.9

**Comment by devny** [comment]
@cgmaier 

Hello! We're waiting for a fix as we continue to look for ways.
Can you tell me when it will be fixed and if the update is due?

**Comment by cgmaier** [comment]
hey @devny I'm planning on taking another look at this today.

**Comment by cgmaier** [comment]
hey all, I made a video of installing GIPHY SDK via Carthage, and subsequently running it on Xcode 11.1, 11.5.1, and 12 Beta. Hope this helps! 
 
[![Alt text](https://img.youtube.com/vi/REYWFhgSZrU/0.jpg)](https://www.youtube.com/watch?v=REYWFhgSZrU&feature=youtu.be)
 
 
cc @devny

**Comment by ezzz** [comment]
Import is OK now. I had to update Carthage binary to 0.35 to override import error with non maching Swift version between Giphy binary and Xcode
Thanks also for the video, very helpful
This issue can be closed for me

I have another issue now but related to the code itself. I will create another discussion for it :)
