### ISSUE TITLE
GiphyGridController and Recents not working

### ISSUE THREAD

**Issue by 3arrett** [Giphy/giphy-ios-sdk-ui-example#87]
SDK Version: 2.0.1
Related: https://github.com/Giphy/giphy-ios-sdk-ui-example/blob/master/Docs.md#recents

I've been working on implementing recents within the `GiphyGridController`. My process is I generally run and select the first few trending GIFs through the picker and then switch to recents by setting the `.content = .recents` and `update()` and it returns 0 results. 

I've also looked at printing out `GPHRecents.count` for debugging but it doesn't compile (is it still internal/private to the SDK?). 

I've looked through the headers too and didn't find anything to further help me. Would like some insight if it's something I'm missing. Thanks!

**Comment by cgmaier** [comment]
hey @3arrett - good catch. looks like we only add a GIF to recents if it's selected from the `GiphyViewController`. I'll include a fix in the next release!

**Comment by cgmaier** [comment]
hi @3arrett this should be fixed in v2.0.2. thanks ! 
https://github.com/Giphy/giphy-ios-sdk-ui-example/releases/tag/v2.0.2

**Comment by 3arrett** [comment]
@cgmaier I just go to integrating this and worked great 👍 

Only thing that's missing is that `GPHRecents.count` still isn't exposed publicly. We'd like to hide our recents button until there are any to show.
